name:                payment-server
version:             0.1.0.0
github:              "wuan/payment-server-experiments"
license:             MIT
author:              "Andreas Wuerl"
maintainer:          "example@example.com"
copyright:           "2022 Andreas Wuerl"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wuan/githubuser/payment-server-experiments>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- transformers
- time
- fast-logger
- servant
- servant-server
- http-media
- wai
- wai-logger
- warp
- stripe-core
- stripe-haskell
- aeson

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  payment-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - payment-server

tests:
  payment-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - payment-server
